upper limit flax version
In Flax version 0.7.1 and later, the flax.linen.Module no longer supports the .unfreeze() method. This change results in an error in the file /pesnet/nn/pesnet.py at line 313, where fermi_params = ferminet.init(subkey, electrons, atoms).unfreeze() is causing an AttributeError: 'dict' object has no attribute 'unfreeze'. As a result, the maximum supported Flax version is restricted to 0.7.0.